# Super awesome script to add new parks quicker
# Also my first ever Ruby creation... Loving Ruby real hard
# Enter some info about the park, then the rest is generated by
# whatever image files are in tours/[city]/tmp

require 'fileutils'

# http://stackoverflow.com/questions/14251311/capitalizing-titles
def titleize(name)
  lowercase_words = %w{a an the and but or for nor of}
  name.split.each_with_index.map{|x, index| lowercase_words.include?(x) && index > 0 ? x : x.capitalize }.join(" ")
end

puts '*******************************************'
puts '*           Cool Park Post Maker          *'
puts '*******************************************'
puts ''

# Ask for the park name
print('(1/8) Enter park name: ')
name = gets.chomp
puts ''

# Ask for slug
print '(2/8) Enter park slug: '
slug = gets.chomp
puts ''

# Ask for the city
print('(3/8) Enter city name: ')
city = gets.chomp
citySlug = city.downcase.gsub(' ', '-')
puts ''

# Ask for the province
print('(4/8) Enter province: ')
province = gets.chomp
puts ''

# Ask for flag
print('(5/8) Enter flag code: ')
flag = gets.chomp
puts ''

# Ask for date
print('(6/8) Enter date (yyyy-mm-dd): ')
date = gets.chomp
puts ''

# Ask for lat
print('(7/8) Enter lat: ')
lat = gets.chomp
puts ''

# And finally the long
print ('(8/8) Enter long: ')
long = gets.chomp
puts ''

# Make basic page post
postPath = '_posts/'+citySlug+'/'+slug
pagePostPath = postPath+'/'+date+'-'+slug+'-page.md'
puts 'Building page markdown file '+pagePostPath

FileUtils::mkdir_p postPath
pagePostFile = File.new(pagePostPath, "w")

pagePostFile.puts '---'
pagePostFile.puts 'layout: park_gallery'
pagePostFile.puts 'permalink: /'+citySlug+'/'+slug
pagePostFile.puts 'date: '+date
pagePostFile.puts 'category: park'
pagePostFile.puts ''
pagePostFile.puts '# Park Page Info'
pagePostFile.puts 'title: '+name
pagePostFile.puts 'city: '+city
pagePostFile.puts 'province: '+province
pagePostFile.puts 'flag: '+flag
pagePostFile.puts 'bannerImg: /tours/'+citySlug+'/tmp/banner.jpg'
pagePostFile.puts ''
pagePostFile.puts '# Shop Info (optional)'
pagePostFile.puts 'shopLogo:'
pagePostFile.puts 'shopDesc:'
pagePostFile.puts 'shopURL:'
pagePostFile.puts 'shopPhone:'
pagePostFile.puts 'shopAddress:'
pagePostFile.puts ''
pagePostFile.puts '# Pano Tour Links'
pagePostFile.puts 'tourLinks:'

# Now let's add all the images in ./tours/[city]/tmp
tmpImgs = Dir['tours/'+citySlug+'/tmp/*']
tmpImgs.each do |filename|
  img = File.basename(filename)
  next if img == 'banner.jpg'
  pagePostFile.puts '  - '+img.gsub('.jpg', '')
end

# Then more static stuff
pagePostFile.puts ''
pagePostFile.puts '# Geographic Info'
pagePostFile.puts 'lat: '+lat
pagePostFile.puts 'long: '+long
pagePostFile.puts ''
pagePostFile.puts '# Youtube Video IDs'
pagePostFile.puts 'videos:'
pagePostFile.puts '---'

# Okay one file done! Next the tour post
tourPostPath = postPath+'/'+date+'-'+slug+'-tour.md'
puts 'Building tour markdown file '+tourPostPath

tourPostFile = File.new(tourPostPath, 'w')

tourPostFile.puts '---'
tourPostFile.puts 'layout: tour'
tourPostFile.puts 'permalink: /'+citySlug+'/'+slug+'/tour'
tourPostFile.puts 'date: '+date
tourPostFile.puts 'category: tour'
tourPostFile.puts ''
tourPostFile.puts '# Pano Tour Info'
tourPostFile.puts 'panoManifest: /tours/'+citySlug+'/'+slug+'.json'
tourPostFile.puts '---'

# Two files! Now on to the shell of the 'pano manifest'
tourConfig = 'tours/'+citySlug+'/'+slug+'.json'
puts 'Building tour config file '+tourConfig
tour = File.new(tourConfig, 'w')
tour.puts '{'
tour.puts '    "default": {'
tour.puts '        "author": "Kirk M.",'
tour.puts '        "firstScene": "entrance",'
tour.puts '        "sceneFadeDuration": 500,'
tour.puts '        "autoLoad": true'
tour.puts '    },'
tour.puts ''
tour.puts '    "scenes": {'

# Loop through the images again and add them all as scenes
tmpImgs.each_with_index do |filename, i|
  img = File.basename(filename)
  next if img == 'banner.jpg'

  sceneTitle = titleize(img.gsub('.jpg', '').gsub('-', ' '))
  tour.puts '        "'+img.gsub('.jpg', '')+'": {'
  tour.puts '            "title": "'+sceneTitle+'",'
  tour.puts '            "panorama": "./tmp/'+img+'",'
  tour.puts '            "hotSpots": ['
  tour.puts '            '
  tour.puts '            ]'
  if i == tmpImgs.length - 1
    tour.puts '        }'
  else
    tour.puts '        },'
  end
end

# Close up all our braces
tour.puts '    }'
tour.puts '}'